name: universe
description: The easy & flexible way to use interactive maps in Flutter. Inspired by Leaflet.js.
version: 1.1.2-nullsafety
# author: Salman S
homepage: https://salkuadrat.github.io/universe
repository: https://github.com/salkuadrat/universe

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  tuple: ^2.0.0
  logging: ^1.0.2
  vector_math: ^2.1.1
  proj4dart: ^2.0.0
  flutter_svg: ^0.23.0+1
  html_unescape: ^2.0.0
  provider: ^6.0.1
  location: ^4.3.0
  geocode: ^1.0.1
  flutter_image: ^4.1.0
  video_player: ^2.2.6
  extended_image: ^8.0.0
  cached_network_image: ^3.2.0
  curved_animation_controller: ^1.1.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  flutter: ">=1.24.0-10.2.pre"
  sdk: ">=2.12.0 <3.3.9"

flutter:
  assets:
    - assets/marker.svg
    - assets/compass.svg
  plugin:
    platforms:
      android:
        package: com.salkuadrat.universe
        pluginClass: UniversePlugin
      ios:
        pluginClass: UniversePlugin
